### ISSUE TITLE
应用里用的高德地图，手机里是百度地图，不知是否做了坐标系转换兼容？

### ISSUE THREAD

**Issue by sth0409** [songhanghang/redcord#1]
应用里用的高德地图，手机里是百度地图，不知是否做了坐标系转换兼容？
app内高德显示想聚10米 拉起的百度地图导航却好远

**Comment by songhanghang** [comment]
感谢反馈, 晚上我验证下...

**Comment by songhanghang** [comment]
> 应用里用的高德地图，手机里是百度地图，不知是否做了坐标系转换兼容？
> app内高德显示想聚10米 拉起的百度地图导航却好远

感谢反馈，之前确实有问题，
现已对坐标系进行转换，百度导航可以正常使用，并提供高德和百度地图的自由选择。
请下载最新版体验 [https://www.pgyer.com/O2dK](https://www.pgyer.com/O2dK)
