### ISSUE TITLE
打赏功能失效

### ISSUE THREAD

**Issue by 1007307796** [songhanghang/redcord#2]
支付宝打赏功能失效，点击打赏后跳转到支付宝页面后，不会响应任何信息

**Comment by songhanghang** [comment]
你好，看到这条年度最感动人心的issues， 着实感动好大会儿！
非常感谢你使用该app， 你手机是什么型号？ 我手头只有小米的机器，test都是ok的哈？
如果还不能打赏的话，加我微信吧 15321290971 mi-宋航
